version: 0.0
os: linux

files:
  - source: /build.zip
    destination: /var/www/healthc2u-admin/

hooks:
    BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: root
    AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: root
    ApplicationStart:
    - location: start_app.sh
      timeout: 300
      runas: root
